[package]
name = "pseudotime"
version = "0.1.0"
edition = "2021"

[dependencies]
abi_stable = "0.11.3"
chrono = "0.4.39"
datetime-parser = { path = "../datetime-parser" }
padamo-api = { path = "../padamo-api"}
