[package]
name = "padamo-transforms"
version = "0.1.0"
edition = "2024"

[lib]
name = "padamotransforms"
crate-type = ["dylib"]

[dependencies]
abi_stable = "0.11.3"
# Main padamo api
padamo-api = { path = "../padamo-api", features = [] }
